mensajes/urls.py
from django.contrib import admin
from django.urls import path
from .views import CreateMensajeView, ConversacionesView, ConversacionesDetailView, contestar_mensaje, eliminar_mensaje, eliminar_conversacion


app_name = 'mensajes'

urlpatterns = [
    path('conversaciones/', ConversacionesView.as_view(), name = 'conversaciones'),
    path('conversaciones-detail/<pk>', ConversacionesDetailView.as_view(), name = 'conversaciones_detail'),
    path('nuevo/<pk>/', CreateMensajeView.as_view(), name = 'nuevo'),
    path('contestar-mensaje/<pk>/', contestar_mensaje, name = 'contestar_mensaje'),
    path('eliminar-mensaje/<pk>/', eliminar_mensaje, name = 'eliminar_mensaje'),
    path('eliminar-conversacion/<pk>/', eliminar_conversacion, name = 'eliminar_conversacion'),
] 

publicaciones/urls.py
from django.contrib import admin
from django.urls import path
from .views import CrearPublicacionView, DetailPublicacionView, UpdatePublicacionView, DeletePublicacionView, like_ajax, contestar_comentario_ajax, eliminar_comentario, eliminar_respuesta_comentario


app_name = 'publicaciones'

urlpatterns = [
    path('like/<pk>/', like_ajax, name = 'like'),
    path('contestar-comentario/<pk>/', contestar_comentario_ajax, name = 'contestar_comentario'),
    path('eliminar-comentario/<pk>/', eliminar_comentario, name = 'eliminar_comentario'),
    path('eliminar-respuesta-comentario/<pk>/', eliminar_respuesta_comentario, name = 'eliminar_respuesta'),
    path('crear/', CrearPublicacionView.as_view(), name = 'crear'),
    path('detalle/<pk>', DetailPublicacionView.as_view(), name = 'detalle'),
    path('editar/<pk>', UpdatePublicacionView.as_view(), name = 'editar'),
    path('eliminar/<pk>', DeletePublicacionView.as_view(), name = 'delete'),
] 

stellarblade/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import legal_view, logout_view, RegisterView, LoginView, HomeView, search_view, PersonalizarReseteoContraseña, info_del_juego, politica_legal
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns#tenemos que importar esto para que funcione la traduccion


urlpatterns = [#aqui metemos las que no queremos que sean traducibles
    path('i18n/', include('django.conf.urls.i18n')),#esto nos incluye la vista set_language,viene propia de django
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += i18n_patterns (
    path('', HomeView.as_view(), name = 'home'),
    path('informacion-stellar-blade/', info_del_juego, name = 'info_del_juego'),
    path('politica-legal/', politica_legal, name = 'politica_legal'),
    path('logout/', logout_view, name = 'logout'),
    path('search/', search_view, name = 'search'),
    path('registro/', RegisterView.as_view(), name = 'registro'),
    path('login/', LoginView.as_view(), name = 'login'),
    path('usuarios/', include('usuarios.urls', namespace = 'usuarios')),
    path('publicaciones/', include('publicaciones.urls', namespace = 'publicaciones')),
    path('notificaciones/', include('notificaciones.urls', namespace = 'notificaciones')),
    path('mensajes/', include('mensajes.urls', namespace = 'mensajes')),
    path('password_reset/', PersonalizarReseteoContraseña.as_view(), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('admin/', admin.site.urls),
)

#para que solo se pueda acceder a rosetta si esta instalada en el proyecto
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

usuarios/urls.py
from django.contrib import admin
from django.urls import path
from .views import MyPerfilView, UpdatePerfilView, DeletePerfilView,PublicacionesMisContactosView, follow_perfiles_ajax, PerfilesDetailView

app_name = 'usuarios'

urlpatterns = [
    path('mi-perfil/<pk>/', MyPerfilView.as_view(), name = 'mi_perfil'),
    path('update-perfil/<pk>/', UpdatePerfilView.as_view(), name = 'update'),
    path('delete-perfil/<pk>/',DeletePerfilView.as_view() , name = 'delete'),
    path('publicaciones-mis-contactos/',PublicacionesMisContactosView.as_view() , name = 'mis_contactos'),
    path('follow/<pk>',follow_perfiles_ajax , name = 'follow'),
    path('perfiles-detail/<pk>',PerfilesDetailView.as_view() , name = 'detail'),
] 

stellarblade/forms/register_form.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from usuarios.models import PerfilUsuario
from django.utils.translation import gettext_lazy as _


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput(), label= _('Escriba su contraseña'))
    password_confirm = forms.CharField(widget = forms.PasswordInput(), label= _('Repita su contraseña'))
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password',
            'password_confirm',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = False#ponemos que el email no sea obligatorio

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if password != password_confirm and password != '':
            self.add_error('password_confirm',_('Las contraseñas no coinciden'))

        return cleaned_data

    def save(self, commit = True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])#encriptamoos la contraseña

        if commit:
            user.save()
            PerfilUsuario.objects.create(usuario = user)
        
        return user

stellarblade/forms/search_form.py
from django import forms
from django.utils.translation import gettext_lazy as _

class SearchForm(forms.Form):
    value = forms.CharField(label=_("Introduce la palabra a buscar"), max_length=150)

stellarblade/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, SearchForm
from django.views.generic import CreateView, FormView, ListView
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.http import HttpResponse, HttpResponseRedirect
from publicaciones.models import Publicacion, Comentario, RespuestaComentario
from usuarios.models import Follow, PerfilUsuario
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.core.exceptions import PermissionDenied
from django.utils.translation import gettext_lazy as _


class HomeView(ListView):
    template_name = 'general/home.html'
    model = Publicacion

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["publicaciones"] = Publicacion.objects.all().exclude(autor=self.request.user.perfil).order_by('-fecha_publicacion') 
        else:
            context["publicaciones"] = Publicacion.objects.all().order_by('-fecha_publicacion')
        return context

def legal_view(request):
    return render(request, 'general/legal.html')

@login_required
def logout_view(request):
    logout(request)
    messages.success(request, _('Sesion cerrada con exito'))
    return HttpResponseRedirect(reverse_lazy('login'))

class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'general/registro.html'
    success_url = reverse_lazy('login')


    #redirigimos al usuario a su perfil en caso de que este logeado
    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            pk = self.request.user.perfil.pk
            return redirect(reverse_lazy('usuarios:mi_perfil' , kwargs={'pk': pk}))
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        messages.success(self.request, _('Usuario creado correctamente'))
        return super().form_valid(form)


class LoginView(FormView):
    template_name = 'general/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('home')

    #redirigimos al usuario a su perfil en caso de que este logeado
    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            pk = self.request.user.perfil.pk
            return redirect(reverse_lazy('usuarios:mi_perfil' , kwargs={'pk': pk}))
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        recuerdame = self.request.POST.get('recuerdame')
        if recuerdame:
            self.request.session.set_expiry(1209600)

        #obtenemos el usuario y comprobamos que ese usuario y contraseña coincide con alguno en la base de datos
        user = form.get_user()
        login(self.request, user)
        messages.success(self.request, _('Inicion de sesion exitoso.'))
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _('Contraseña o usuario incorrectos.'))
        return HttpResponseRedirect(reverse_lazy('login'))
        super().form_invalid(form)

@login_required
def search_view(request):
    if request.GET:
        formulario = SearchForm(request.GET)

        busqueda = formulario.data['value']#obtenemos lo que haya en el campo value del formulario

        publicaciones = Publicacion.objects.filter(titulo__icontains=busqueda)
        usuarios = PerfilUsuario.objects.filter(usuario__username__icontains=busqueda).exclude(usuario=request.user)# de esta forma accedemos al modelo PerfilUsuario para utilizar el include de _perfiles.html
        comentarios = Comentario.objects.filter(texto__icontains=busqueda)

        context ={
            'publicaciones': publicaciones,
            'usuarios': usuarios,
            'comentarios': comentarios,
            'formulario': formulario,
        }

        return render(request, 'general/busqueda.html', context)
    else:
        formulario = SearchForm()

        context = {
            'formulario': formulario
        }

        return render(request, 'general/busqueda.html', context)


#clase para personalizar los templates de recuperacion de contraseña
class PersonalizarReseteoContraseña(PasswordResetView):
    email_template_name = 'registration/password_reset_email.html'
    success_url = reverse_lazy('password_reset_done')
    template_name = 'registration/password_reset_form.html'


def info_del_juego(request):
    return render(request, 'general/info_del_juego.html')

def politica_legal(request):
    return render(request, 'general/politica_legal.html')

usuarios/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, FormView, DetailView, UpdateView, DeleteView, ListView
from .models import PerfilUsuario, Follow
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User
from django.http import JsonResponse
from publicaciones.models import Publicacion
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from notificaciones.models import NotificacionSeguir
from stellarblade.forms import PerfilUsuarioForm
from django.utils.translation import gettext_lazy as _

class MyPerfilView(DetailView):
    model = PerfilUsuario
    template_name = 'usuarios/mi_perfil.html'

    def dispatch(self, request, *args, **kwargs):
        usuario_perfil = self.get_object()
        if usuario_perfil.usuario != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["perfil"] = PerfilUsuario.objects.get(pk=self.object.pk)
        context["publicaciones"] = Publicacion.objects.filter(autor = self.request.user.perfil).order_by('-fecha_publicacion')
        return context


@method_decorator(login_required, name='dispatch')
class UpdatePerfilView(UpdateView):
    template_name = 'usuarios/perfil_update.html'
    model = PerfilUsuario
    form_class = PerfilUsuarioForm

    def dispatch(self, request, *args, **kwargs):
        usuario_perfil = self.get_object()
        if usuario_perfil.usuario != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)
    

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user#pasamos el usuario al formulario
        return kwargs

    def form_valid(self, form):
        messages.success(self.request, _('Usuario editado correctamente.'))
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('usuarios:mi_perfil', kwargs={'pk': self.object.pk})


@method_decorator(login_required, name='dispatch')
class DeletePerfilView(DeleteView):
    model = PerfilUsuario
    template_name = 'usuarios/perfil_delete.html'
    success_url = reverse_lazy('registro')

    def dispatch(self, request, *args, **kwargs):
        usuario_perfil = self.get_object()
        if usuario_perfil.usuario != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        usuario = User.objects.get(username = self.object.usuario)
        usuario.delete()
        messages.success(self.request, _('Perfil eliminado correctamente'))
        return super().form_valid(form)


@method_decorator(login_required, name="dispatch")
class PublicacionesMisContactosView(ListView):
    model = Publicacion
    template_name = 'usuarios/publicaciones_mis_contactos.html'
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #obtenemos el perfil de usuario logeado
        perfil_usuario = self.request.user.perfil
        #obtenemos a los usuarios que sigue el usuario logeado
        usuario_seguidos = perfil_usuario.seguidores.all()
        #lo filtramos para que salgan los que el autor de las publicaciones esten en los usuarios seguidos del usuario logeado
        context ["publicaciones"] = Publicacion.objects.filter(autor__in=usuario_seguidos).order_by('-fecha_publicacion')
        
        return context


@login_required
def follow_perfiles_ajax(request, pk):
    perfil = PerfilUsuario.objects.get(pk = pk)
    if Follow.objects.filter(seguidor = request.user.perfil, siguiendo = perfil).count():
        request.user.perfil.unfollow(perfil)
        NotificacionSeguir.objects.filter(destinatario=perfil, usuario=request.user.perfil, url=reverse_lazy('usuarios:detail', kwargs={'pk': request.user.perfil.pk})).delete()
        return JsonResponse({
            'mensaje': _('Se ha dejado de seguir al usuario: %(usuario)s') % {
                'usuario': perfil.usuario
            },
            'follow': False,
            'numero_seguidores': perfil.siguiendo.count()
        })
    else:
        request.user.perfil.follow(perfil)
        NotificacionSeguir.objects.create(destinatario=perfil, usuario=request.user.perfil, url=reverse_lazy('usuarios:detail', kwargs={'pk': request.user.perfil.pk}))
        return JsonResponse ({
            'mensaje': _('Se ha empezado a seguir al usuario: %(usuario)s') % {
                'usuario': perfil.usuario
            },
            'follow': True,
            'numero_seguidores': perfil.siguiendo.count()
        })


class PerfilesDetailView(DetailView):
    template_name = 'usuarios/perfiles_detail.html'
    model = PerfilUsuario
    context_object_name = 'perfil'

    def dispatch(self, request, *args, **kwargs):
        #evita que accedamos a detalle perfil del usuario logeado, nos redirige a nuestro perfil
        pk = self.kwargs.get('pk')
        usuario_perfil = PerfilUsuario.objects.get(pk=pk)
        if usuario_perfil.usuario == self.request.user:
            return redirect(reverse_lazy('usuarios:mi_perfil' , kwargs={'pk': pk}))
        return super().dispatch(request, *args, **kwargs)

stellarblade/templates/usuarios/mi_perfil.html
{% extends "general/layout.html" %}
{% load i18n %}
{% block head_title %}Stellar Blade{% endblock  %}
{% block description %}{{perfil.usuario}}- {{perfil.biografia|truncatechars:20}}{% endblock %}
{% block page_title %}{% trans "MI PERFIL" %}{% endblock  %}
{% block page_content %}
<div class="container-mi-perfil">
    <article class="mi-perfil-top" >
        {% if perfil.imagen_perfil %}
            <img src="{{perfil.imagen_perfil.thumbnails.medium.url}}" alt="{{perfil.usuario}}">
        {% else %}
            <i class="bi bi-person-circle"></i>
        {% endif %}
        <div class="descripcion-mi-perfil">
            <div class="editar-eliminar-mi-perfil">
                <p><strong>{{perfil.usuario}}</strong></p>
                {% if request.user.perfil.usuario == perfil.usuario %}
                <a class="boton-editar" href="{% url 'usuarios:update' perfil.pk %}">{% trans "Editar Perfil" %}</a>
                <a class="boton-eliminar" href="{% url 'usuarios:delete' perfil.pk %}">{% trans "Eliminar perfil" %}</a>
                {% endif %}
            </div>
            <div class="crear-publicacion-cerrar-sesion-mi-perfil">
                {% if request.user.perfil.usuario == perfil.usuario %}
                <a class="boton-crear-publicacion" href="{% url 'publicaciones:crear' %}">{% trans "Crear publicación" %}</a>
                <a class="boton-cerrar-sesion" href="{% url 'logout' %}">{% trans "Cerrar sesión" %}</a>
                {% endif %}
            </div>
            <div class="seguidores-seguidos-mi-perfil">
                <p>{% trans "Seguidores:" %}<span>{{perfil.siguiendo.count}}</span></p>
                <p>{% trans "Siguiendo:" %}<span>{{perfil.seguidores.count}}</span></p>
            </div>
            <div class="biografia-mi-perfil">
                <p>{{perfil.biografia}}</p>
            </div>
        </div>
    </article>
    <div class="container-mis-ultimas-publicaciones">
        <h3>{% trans "Mis últimas publicaciones" %}</h3>
        <div class="mis-ultimas-publicaciones">
            {% for publicacion in publicaciones %}
                {% include "_includes/_publicaciones.html" %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock  %}

stellarblade/templates/usuarios/perfil_delete.html
{% extends "general/layout.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block head_title %}Stellar Blade{% endblock  %}
{% block description %}{% trans "Pagina de eliminación de perfil de usuario" %}{% endblock %}
{% block page_title %}{% trans "ELIMINAR PERFIL" %}{% endblock  %}
{% block page_content %}
<div class="container-eliminar-perfil">
    <h4 class="title-eliminar-perfil" >{% trans "¿Seguro que desea eliminar su perfil:" %} <strong>{{object.usuario}}</strong>?</h4>
    <form class="formulario-borrar-perfil" action="" method = 'POST'>
    {% csrf_token %}
    {{form}}
    <button class="boton-eliminar">{% trans "Eliminar" %}</button>
    <a class="boton-cancelar" href="{% url 'usuarios:mi_perfil' object.pk %}">{% trans "Cancelar" %}</a>
    </form>
</div>
{% endblock  %}

stellarblade/templates/usuarios/perfil_update.html
{% extends "general/layout.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block head_title %}Stellar Blade{% endblock  %}
{% block description %}{% trans "Pagina de edición de perfil de usuario" %}{% endblock %}
{% block page_title %}{% trans "EDITA TU PERFIL" %}{% endblock  %}
{% block page_content %}
    <div class="container-editar-perfil">
        <form class="formulario-editar-perfil" action="" method='POST' enctype='multipart/form-data'>
            {% csrf_token %}
            {{form.imagen_perfil | as_crispy_field}}
            {{form.email | as_crispy_field}}
            {{form.biografia | as_crispy_field}}
            {{form.fecha_nacimiento | as_crispy_field}}
            <button class="boton-editar">{% trans "Actualizar usuario" %}</button>
            <a class="boton-cancelar" href="{% url 'usuarios:mi_perfil' request.user.perfil.pk %}">{% trans "Cancelar" %}</a>
        </form>
    </div>
{% endblock  %}

stellarblade/templates/usuarios/perfiles_detail.html
{% extends "general/layout.html" %}
{% load i18n %}
{% block head_title %}Stellar Blade{% endblock  %}
{% block description %}{{perfil.usuario}} - {{perfil.biografia}}{% endblock %}
{% block page_title %}{% trans "DETALLE DE PERFIL" %}{% endblock %}
{% block page_content %}
<div class="container-perfiles-detail">
    <article class="perfiles-detail" >
        {% if perfil.imagen_perfil %}
                <img src="{{perfil.imagen_perfil.thumbnails.medium.url}}" alt="{{perfil.usuario}}">
        {% else %}
            <i id="icon-user" class="bi bi-person-circle"></i>
        {% endif %}
        <div class="descripcion-perfiles-detail">
            <div class="seguidores-siguiendo-mensaje">
                <p class='seguidores' id="Nseguidores-{{perfil.pk}}">{% trans "Seguidores:" %}<span>{{perfil.siguiendo.count}}</span></p>
                <p class="siguiendo">{% trans "Siguiendo:" %}<span>{{perfil.seguidores.count}}</span></p>
                <a class="mensaje" href="{% url 'mensajes:nuevo' perfil.pk %}"><i class="bi bi-envelope"></i></a>
            </div>
            <div class="nombre-te-sigue">
                <p><strong>{{perfil.usuario}}</strong></p>
                {% if perfil in request.user.perfil.siguiendo.all  %}
                    <span>{% trans "Te sigue" %}</span>
                {% endif %}
            </div>
            <div class="biografia-perfiles-detail">
                <p>{{perfil.biografia}}</p>
            </div>
            <div class="botones-seguir-dejar-de-seguir">
                <a class='ButtonFollows' data-perfil-id='{{perfil.pk}}' href="{% url 'usuarios:follow' perfil.pk %}">
                    {% if request.user.perfil in perfil.siguiendo.all %}
                        <button class="boton-dejar-de-seguir">{% trans "Dejar de seguir" %}</button>
                    {% else %}
                        <button class="boton-seguir">{% trans "Seguir" %}</button>
                    {% endif %}
                </a>
            </div>
        </div>
    </article>
    <div class="container-ultimas-publicaciones-perfiles-detail">
        <h3 class="title-ultimas-publicaciones-perfiles-detail">{% trans "Ultimas publicaciones" %}</h3>
        <div class="ultimas-publicaciones-perfiles-detail">
            {% for publicacion in perfil.publicaciones.all %}
                    {% include "_includes/_publicaciones.html" %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock  %}

stellarblade/templates/usuarios/publicaciones_mis_contactos.html
{% extends "general/layout.html" %}
{% load i18n %}
{% block head_title %}Stellar Blade{% endblock  %}
{% block description %}{% trans "Pagina de ultimas publicaciones de mis contactos" %}{% endblock %}
{% block page_title %}{% trans "MI RED" %}{% endblock %}
{% block page_content %}
{% if publicaciones %}
    <h2 class="title-contactos">{% trans "Publicaciones de mis contactos" %}</h2>
    <div class="container-publicaciones-mis-contactos">
        {% for publicacion in publicaciones %}
            {% include "_includes/_publicaciones.html" %}
        {% endfor %}
    </div>
{% else %}
    <h2 class="title-sin-contactos">{% trans "Aún no sigues a nadie" %}</h2>
{% endif %}
{% endblock  %}