mensajes/urls.py
from django.contrib import admin
from django.urls import path
from .views import CreateMensajeView, ConversacionesView, ConversacionesDetailView, contestar_mensaje, eliminar_mensaje, eliminar_conversacion


app_name = 'mensajes'

urlpatterns = [
    path('conversaciones/', ConversacionesView.as_view(), name = 'conversaciones'),
    path('conversaciones-detail/<pk>', ConversacionesDetailView.as_view(), name = 'conversaciones_detail'),
    path('nuevo/<pk>/', CreateMensajeView.as_view(), name = 'nuevo'),
    path('contestar-mensaje/<pk>/', contestar_mensaje, name = 'contestar_mensaje'),
    path('eliminar-mensaje/<pk>/', eliminar_mensaje, name = 'eliminar_mensaje'),
    path('eliminar-conversacion/<pk>/', eliminar_conversacion, name = 'eliminar_conversacion'),
] 

stellarblade/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import legal_view, logout_view, RegisterView, LoginView, HomeView, search_view, PersonalizarReseteoContraseña, info_del_juego, politica_legal
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns#tenemos que importar esto para que funcione la traduccion


urlpatterns = [#aqui metemos las que no queremos que sean traducibles
    path('i18n/', include('django.conf.urls.i18n')),#esto nos incluye la vista set_language,viene propia de django
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += i18n_patterns (
    path('', HomeView.as_view(), name = 'home'),
    path('informacion-stellar-blade/', info_del_juego, name = 'info_del_juego'),
    path('politica-legal/', politica_legal, name = 'politica_legal'),
    path('logout/', logout_view, name = 'logout'),
    path('search/', search_view, name = 'search'),
    path('registro/', RegisterView.as_view(), name = 'registro'),
    path('login/', LoginView.as_view(), name = 'login'),
    path('usuarios/', include('usuarios.urls', namespace = 'usuarios')),
    path('publicaciones/', include('publicaciones.urls', namespace = 'publicaciones')),
    path('notificaciones/', include('notificaciones.urls', namespace = 'notificaciones')),
    path('mensajes/', include('mensajes.urls', namespace = 'mensajes')),
    path('password_reset/', PersonalizarReseteoContraseña.as_view(), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('admin/', admin.site.urls),
)

#para que solo se pueda acceder a rosetta si esta instalada en el proyecto
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

usuarios/urls.py
from django.contrib import admin
from django.urls import path
from .views import MyPerfilView, UpdatePerfilView, DeletePerfilView,PublicacionesMisContactosView, follow_perfiles_ajax, PerfilesDetailView

app_name = 'usuarios'

urlpatterns = [
    path('mi-perfil/<pk>/', MyPerfilView.as_view(), name = 'mi_perfil'),
    path('update-perfil/<pk>/', UpdatePerfilView.as_view(), name = 'update'),
    path('delete-perfil/<pk>/',DeletePerfilView.as_view() , name = 'delete'),
    path('publicaciones-mis-contactos/',PublicacionesMisContactosView.as_view() , name = 'mis_contactos'),
    path('follow/<pk>',follow_perfiles_ajax , name = 'follow'),
    path('perfiles-detail/<pk>',PerfilesDetailView.as_view() , name = 'detail'),
] 

mensajes/forms.py
from django import forms
from .models import Mensaje

#formulario que crea nuevos mensajes
class CreateMensajeForm(forms.ModelForm):
    class Meta:
        model = Mensaje
        fields = [
            'contenido',
        ]

#formulario para contestar mensajes
class ContestarMensajeForm(forms.ModelForm):
    class Meta:
        model = Mensaje
        fields = [
            'contenido',
        ]

stellarblade/forms/register_form.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from usuarios.models import PerfilUsuario
from django.utils.translation import gettext_lazy as _


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput(), label= _('Escriba su contraseña'))
    password_confirm = forms.CharField(widget = forms.PasswordInput(), label= _('Repita su contraseña'))
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password',
            'password_confirm',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = False#ponemos que el email no sea obligatorio

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if password != password_confirm and password != '':
            self.add_error('password_confirm',_('Las contraseñas no coinciden'))

        return cleaned_data

    def save(self, commit = True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])#encriptamoos la contraseña

        if commit:
            user.save()
            PerfilUsuario.objects.create(usuario = user)
        
        return user

stellarblade/forms/search_form.py
from django import forms
from django.utils.translation import gettext_lazy as _

class SearchForm(forms.Form):
    value = forms.CharField(label=_("Introduce la palabra a buscar"), max_length=150)

mensajes/views.py
from django.shortcuts import render
from django.views.generic import CreateView, FormView, DetailView, UpdateView, DeleteView, ListView
from usuarios.models import PerfilUsuario, Follow
from publicaciones.models import Publicacion, Comentario, RespuestaComentario
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from notificaciones.models import NotificacionPublicacion, NotificacionComentario, NotificacionRespuestaComentario, NotificacionMeGusta, NotificacionSeguir, NotificacionMensaje
from .models import Mensaje, Conversacion
from .forms import CreateMensajeForm
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.utils.translation import gettext_lazy as _

@method_decorator(login_required, name='dispatch')
class CreateMensajeView(CreateView):
    template_name = 'mensajes/nuevo_mensaje.html'
    model = Mensaje
    form_class = CreateMensajeForm


    def dispatch(self, request, *args, **kwargs):
        #en caso de que se intente mandar un mensaje a si mismo, no nos deja
        pk = self.kwargs.get('pk')
        usuario_perfil = PerfilUsuario.objects.get(pk=pk)
        if usuario_perfil.usuario == self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        pk = self.kwargs.get('pk')#obtenemos el pk de la url, que guardamos antes que corresponde al perfil que estemos viendo
        destinatario = PerfilUsuario.objects.get(pk = pk)
        conversacion = Conversacion.objects.create(usuario1=self.request.user.perfil, usuario2 = destinatario)
        nuevo_mensaje = form.save(commit=False)
        nuevo_mensaje.autor = self.request.user.perfil
        nuevo_mensaje.destinatario = destinatario
        nuevo_mensaje.conversacion = conversacion
        nuevo_mensaje.save()

        NotificacionMensaje.objects.create(destinatario=destinatario, usuario=self.request.user.perfil, mensaje=nuevo_mensaje, conversacion=conversacion, url= reverse_lazy('mensajes:conversaciones_detail', kwargs={'pk': conversacion.pk}))

        messages.success(self.request, _('Mensaje enviado correctamente'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('mensajes:conversaciones')


@method_decorator(login_required, name='dispatch')
class ConversacionesView(ListView):
    template_name = 'mensajes/conversaciones.html'
    model = Conversacion

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["conversaciones"] = Conversacion.objects.filter(
            Q(usuario1 = self.request.user.perfil) | Q(usuario2 = self.request.user.perfil)#obtenemos todas las conversaciones, ya seamos el que la ha iniciado o no
            )
        
        return context


@method_decorator(login_required, name='dispatch')
class ConversacionesDetailView(DetailView):
    template_name = 'mensajes/conversaciones_detail.html'
    model = Conversacion
    context_object_name = 'conversacion'


@login_required
def contestar_mensaje(request, pk):
    if request.method == 'POST':
        mensaje = Mensaje.objects.get(pk = pk)

        conversacion = Conversacion.objects.filter(
            usuario1=mensaje.autor, usuario2=mensaje.destinatario
        ).first() or Conversacion.objects.filter(
            usuario1=mensaje.destinatario, usuario2=mensaje.autor
        ).first()

        if not conversacion:
            return JsonResponse({'success': False, 'error': 'Conversación no encontrada'})
        

        respuesta_mensaje = request.POST.get('contenido')
        if respuesta_mensaje:

            autor_mensaje = request.user.perfil

            destinatario_respuesta = (#comprobamos que siempre se envie al destinatario correspondiente segun el ultimo usuario en contestar
                conversacion.usuario1 if autor_mensaje == conversacion.usuario2 else conversacion.usuario2
            )
            mensaje_respuesta = Mensaje.objects.create(conversacion=conversacion, autor=autor_mensaje, destinatario=destinatario_respuesta, contenido=respuesta_mensaje)

            NotificacionMensaje.objects.create(destinatario=destinatario_respuesta, usuario=autor_mensaje, mensaje=mensaje_respuesta, conversacion=conversacion, url= reverse_lazy('mensajes:conversaciones_detail', kwargs={'pk': conversacion.pk}))
            
            return JsonResponse({
                'success': True
            })
        else:
            return JsonResponse({
                'success': False
            })


@login_required
def eliminar_mensaje(request, pk):
    if request.method == 'DELETE':
        mensaje = Mensaje.objects.get(pk = pk)
        conversacion = Conversacion.objects.get(pk = mensaje.conversacion.pk)
        if request.user.perfil == mensaje.autor:
            notificacion = NotificacionMensaje.objects.filter(destinatario=mensaje.destinatario, usuario=mensaje.autor, conversacion=conversacion, mensaje=mensaje).first()
            notificacion.delete()
            mensaje.delete()
            return JsonResponse({
                'success': True,
                'message': _('Mensaje eliminado corectamente'),
            })
        else:
            return JsonResponse({
                'success': False,
                'message': _('No se ha podido borrar el mensaje'),
            })


@login_required
def eliminar_conversacion(request, pk):
    if request.method == 'DELETE':
        conversacion = Conversacion.objects.get(pk = pk)
        perfil_usuario = request.user.perfil
        if conversacion.usuario1 == perfil_usuario or conversacion.usuario2 == perfil_usuario:#comprobamos que el algunos de usuarios de la conversacion para poder borrarla
            conversacion.delete()
            return JsonResponse({
                'success': True,
                'message': _('Conversacion eliminida correctamente'),
            })
        else:
            return JsonResponse({
                'success': True,
                'message': _('No se ha podido eliminar la conversacion'),
            })

stellarblade/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, SearchForm
from django.views.generic import CreateView, FormView, ListView
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.http import HttpResponse, HttpResponseRedirect
from publicaciones.models import Publicacion, Comentario, RespuestaComentario
from usuarios.models import Follow, PerfilUsuario
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.core.exceptions import PermissionDenied
from django.utils.translation import gettext_lazy as _


class HomeView(ListView):
    template_name = 'general/home.html'
    model = Publicacion

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["publicaciones"] = Publicacion.objects.all().exclude(autor=self.request.user.perfil).order_by('-fecha_publicacion') 
        else:
            context["publicaciones"] = Publicacion.objects.all().order_by('-fecha_publicacion')
        return context

def legal_view(request):
    return render(request, 'general/legal.html')

@login_required
def logout_view(request):
    logout(request)
    messages.success(request, _('Sesion cerrada con exito'))
    return HttpResponseRedirect(reverse_lazy('login'))

class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'general/registro.html'
    success_url = reverse_lazy('login')


    #redirigimos al usuario a su perfil en caso de que este logeado
    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            pk = self.request.user.perfil.pk
            return redirect(reverse_lazy('usuarios:mi_perfil' , kwargs={'pk': pk}))
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        messages.success(self.request, _('Usuario creado correctamente'))
        return super().form_valid(form)


class LoginView(FormView):
    template_name = 'general/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('home')

    #redirigimos al usuario a su perfil en caso de que este logeado
    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            pk = self.request.user.perfil.pk
            return redirect(reverse_lazy('usuarios:mi_perfil' , kwargs={'pk': pk}))
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        recuerdame = self.request.POST.get('recuerdame')
        if recuerdame:
            self.request.session.set_expiry(1209600)

        #obtenemos el usuario y comprobamos que ese usuario y contraseña coincide con alguno en la base de datos
        user = form.get_user()
        login(self.request, user)
        messages.success(self.request, _('Inicion de sesion exitoso.'))
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _('Contraseña o usuario incorrectos.'))
        return HttpResponseRedirect(reverse_lazy('login'))
        super().form_invalid(form)

@login_required
def search_view(request):
    if request.GET:
        formulario = SearchForm(request.GET)

        busqueda = formulario.data['value']#obtenemos lo que haya en el campo value del formulario

        publicaciones = Publicacion.objects.filter(titulo__icontains=busqueda)
        usuarios = PerfilUsuario.objects.filter(usuario__username__icontains=busqueda).exclude(usuario=request.user)# de esta forma accedemos al modelo PerfilUsuario para utilizar el include de _perfiles.html
        comentarios = Comentario.objects.filter(texto__icontains=busqueda)

        context ={
            'publicaciones': publicaciones,
            'usuarios': usuarios,
            'comentarios': comentarios,
            'formulario': formulario,
        }

        return render(request, 'general/busqueda.html', context)
    else:
        formulario = SearchForm()

        context = {
            'formulario': formulario
        }

        return render(request, 'general/busqueda.html', context)


#clase para personalizar los templates de recuperacion de contraseña
class PersonalizarReseteoContraseña(PasswordResetView):
    email_template_name = 'registration/password_reset_email.html'
    success_url = reverse_lazy('password_reset_done')
    template_name = 'registration/password_reset_form.html'


def info_del_juego(request):
    return render(request, 'general/info_del_juego.html')

def politica_legal(request):
    return render(request, 'general/politica_legal.html')

stellarblade/templates/mensajes/conversaciones.html
{% extends "general/layout.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block head_title %}Stellar Blade{% endblock  %}
{% block description %}{% trans "Pagina donde se encuentras las conversaciones, con el que puedes ir directo a los mensajes" %}{% endblock %}
{% block page_title %}{% trans "CONVERSACIONES" %}{% endblock  %}
{% block page_content %}
<div class="container-conversaciones">
    {% if conversaciones %}
    {% for conversacion in conversaciones %}
        <article class="conversacion" id="conversacion-{{conversacion.pk}}" data-pk-conversacion="{{conversacion.pk}}">
            {% if conversacion.usuario1.imagen_perfil %}
                <img src="{{conversacion.usuario1.imagen_perfil.thumbnails.xs.url}}" alt="{{conversacion.usuario1.usuario}}">
            {% else %}
                <i class="bi bi-person-circle"></i>
            {% endif %}
            <div class="conversacion-enlace">
                <p>{{conversacion}}</p>
                <a class="boton-ir-conversacion" href="{% url 'mensajes:conversaciones_detail' conversacion.pk %}">{% trans "Ir a la conversación" %}</a>
            </div>
        </article>
    {% endfor %}
    {% else %}
        <h3>{% trans "Aún no tienes conversaciones" %}</h3>
    {% endif %}
</div>
{% endblock  %}

stellarblade/templates/mensajes/conversaciones_detail.html
{% extends "general/layout.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block head_title %}Stellar Blade{% endblock  %}
{% block description %}{% trans "Pagina que contiene las conversaciones activas del usuario y sus mensajes" %}{% endblock %}
{% block page_title %}{% trans "DETALLE CONVERSACIONES" %}{% endblock  %}
{% block page_content %}
<h2 class="title-conversaciones-detalle">{{conversacion}}</h2>
<div class="container-conversaciones-detail">
    {% for mensajes in conversacion.mensajes.all %}
    {% if mensajes.autor == request.user.perfil %}
        <div class="mensaje-1">
            <div class="imagen-mensaje">
                {% if mensajes.autor.imagen_perfil %}
                    <a href="{% url 'usuarios:detail' mensajes.autor.pk %}">
                        <img src="{{mensajes.autor.imagen_perfil.thumbnails.xs.url}}" alt="{{mensajes.autor.usuario}}" class="imagen-perfil-usuario">
                    </a>
                {% else %}
                    <a href="{% url 'usuarios:detail' mensajes.autor.pk %}">
                        <i class="bi bi-person-circle"></i>
                    </a>
                {% endif %}
                <p>{{mensajes.contenido}}</p>
            </div>
            <div class="fecha-borrar-mensaje">
                <span>{% trans "Hace:" %} {{mensajes.fecha_mensaje | timesince}}</span>
                {% if request.user.perfil == mensajes.autor %}
                <button data-redirect-url="{% url 'mensajes:conversaciones_detail' conversacion.pk %}" data-href="{% url 'mensajes:eliminar_mensaje' mensajes.pk %}" class="eliminar-mensajes" data-mensaje-pk="{{mensajes.pk}}" id="eliminar-mensaje-{{mensajes.pk}}"><i class="bi bi-trash3"></i></button>
                {% endif %}
            </div>
        </div>
    {% else %}
    <div class="mensaje-2">
        <div class="mensaje-imagen">
            <p>{{mensajes.contenido}}</p>
            {% if mensajes.autor.imagen_perfil %}
                <a href="{% url 'usuarios:detail' mensajes.autor.pk %}">
                    <img src="{{mensajes.autor.imagen_perfil.thumbnails.xs.url}}" alt="{{mensajes.autor.usuario}}" class="imagen-perfil-usuario">
                </a>
            {% else %}
                <a href="{% url 'usuarios:detail' mensajes.autor.pk %}">
                    <i class="bi bi-person-circle"></i>
                </a>
            {% endif %}

        </div>
        <div class="borrar-fecha-mensaje">
            {% if request.user.perfil == mensajes.autor %}
            <button data-redirect-url="{% url 'mensajes:conversaciones_detail' conversacion.pk %}" data-href="{% url 'mensajes:eliminar_mensaje' mensajes.pk %}" class="eliminar-mensajes" data-mensaje-pk="{{mensajes.pk}}" id="eliminar-mensaje-{{mensajes.pk}}"><i class="bi bi-trash3"></i></button>
            {% endif %}
            <span>{% trans "Hace:" %} {{mensajes.fecha_mensaje | timesince}}</span>
        </div>
    </div>
    {% endif %}
    {% endfor %}
    {% if conversacion.mensajes.all %}
        <form class="form-contestar-mensaje" action="{% url 'mensajes:contestar_mensaje' conversacion.mensajes.last.pk %}" method='POST' data-redirect-url="{% url 'mensajes:conversaciones_detail' conversacion.pk %}">
            {% csrf_token %}
            {{contestar_mensaje.contenido | as_crispy_field}}
            <button class="boton-contestar">{% trans "Enviar" %}</button>
        </form>
    {% else %}
        <h3 class="title-borrado-conversaciones">{% trans "Se han borrado los mensajes de esta conversacion" %}</h3>
        <button data-href="{% url 'mensajes:eliminar_conversacion' conversacion.pk %}" class="eliminar-conversaciones" data-conversacion-pk="{{conversacion.pk}}" id="eliminar-conversacion-{{conversacion.pk}}" data-redirect-url="{% url 'mensajes:conversaciones' %}" >{% trans "Eliminar conversación" %}</button>
    {% endif %}
</div>
{% endblock  %}

stellarblade/templates/mensajes/nuevo_mensaje.html
{% extends "general/layout.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block head_title %}Stellar Blade{% endblock  %}
{% block description %}{% trans "Creacion de un mensaje nuevo" %}{% endblock %}
{% block page_title %}{% trans "NUEVO MENSAJE" %}{% endblock  %}
{% block page_content %}
<div class="container-nuevo-mensaje">
    <form class="formulario-nuevo-mensaje" action="" method='POST'>
        {% csrf_token %}
        {{form.contenido | as_crispy_field}}
        <button class="boton-enviar" >{% trans "Enviar" %}</button>
    </form>
</div>
{% endblock  %}