mensajes/urls.py
from django.contrib import admin
from django.urls import path
from .views import CreateMensajeView, ConversacionesView, ConversacionesDetailView, contestar_mensaje, eliminar_mensaje, eliminar_conversacion


app_name = 'mensajes'

urlpatterns = [
    path('conversaciones/', ConversacionesView.as_view(), name = 'conversaciones'),
    path('conversaciones-detail/<pk>', ConversacionesDetailView.as_view(), name = 'conversaciones_detail'),
    path('nuevo/<pk>/', CreateMensajeView.as_view(), name = 'nuevo'),
    path('contestar-mensaje/<pk>/', contestar_mensaje, name = 'contestar_mensaje'),
    path('eliminar-mensaje/<pk>/', eliminar_mensaje, name = 'eliminar_mensaje'),
    path('eliminar-conversacion/<pk>/', eliminar_conversacion, name = 'eliminar_conversacion'),
] 

notificaciones/urls.py
from django.contrib import admin
from django.urls import path
from .views import marcar_notificacion_leida_comentario, marcar_notificacion_leida_publicacion, marcar_notificacion_leida_respuesta_comentario, marcar_notificacion_leida_me_gusta, marcar_notificacion_leida_seguir, list_notificaciones, marcar_notificacion_leida_mensajes


app_name = 'notificaciones'

urlpatterns = [
    path('notificaciones/', list_notificaciones, name = 'lista'),
    path('marcar-leida-comentario/<pk>/', marcar_notificacion_leida_comentario, name = 'marcar_leida_comentario'),
    path('marcar-leida-publicacion/<pk>/', marcar_notificacion_leida_publicacion, name = 'marcar_leida_publicacion'),
    path('marcar-leida-respuesta-comentario/<pk>/', marcar_notificacion_leida_respuesta_comentario, name = 'marcar_leida_respuesta_comentario'),
    path('marcar-leida-me-gusta/<pk>/', marcar_notificacion_leida_me_gusta, name = 'marcar_leida_me_gusta'),
    path('marcar-leida-seguir/<pk>/', marcar_notificacion_leida_seguir, name = 'marcar_leida_seguir'),
    path('marcar-leida-mensaje/<pk>/', marcar_notificacion_leida_mensajes, name = 'marcar_leida_mensaje'),
] 

publicaciones/urls.py
from django.contrib import admin
from django.urls import path
from .views import CrearPublicacionView, DetailPublicacionView, UpdatePublicacionView, DeletePublicacionView, like_ajax, contestar_comentario_ajax, eliminar_comentario, eliminar_respuesta_comentario


app_name = 'publicaciones'

urlpatterns = [
    path('like/<pk>/', like_ajax, name = 'like'),
    path('contestar-comentario/<pk>/', contestar_comentario_ajax, name = 'contestar_comentario'),
    path('eliminar-comentario/<pk>/', eliminar_comentario, name = 'eliminar_comentario'),
    path('eliminar-respuesta-comentario/<pk>/', eliminar_respuesta_comentario, name = 'eliminar_respuesta'),
    path('crear/', CrearPublicacionView.as_view(), name = 'crear'),
    path('detalle/<pk>', DetailPublicacionView.as_view(), name = 'detalle'),
    path('editar/<pk>', UpdatePublicacionView.as_view(), name = 'editar'),
    path('eliminar/<pk>', DeletePublicacionView.as_view(), name = 'delete'),
] 

stellarblade/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import legal_view, logout_view, RegisterView, LoginView, HomeView, search_view, PersonalizarReseteoContraseña, info_del_juego, politica_legal
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns#tenemos que importar esto para que funcione la traduccion


urlpatterns = [#aqui metemos las que no queremos que sean traducibles
    path('i18n/', include('django.conf.urls.i18n')),#esto nos incluye la vista set_language,viene propia de django
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += i18n_patterns (
    path('', HomeView.as_view(), name = 'home'),
    path('informacion-stellar-blade/', info_del_juego, name = 'info_del_juego'),
    path('politica-legal/', politica_legal, name = 'politica_legal'),
    path('logout/', logout_view, name = 'logout'),
    path('search/', search_view, name = 'search'),
    path('registro/', RegisterView.as_view(), name = 'registro'),
    path('login/', LoginView.as_view(), name = 'login'),
    path('usuarios/', include('usuarios.urls', namespace = 'usuarios')),
    path('publicaciones/', include('publicaciones.urls', namespace = 'publicaciones')),
    path('notificaciones/', include('notificaciones.urls', namespace = 'notificaciones')),
    path('mensajes/', include('mensajes.urls', namespace = 'mensajes')),
    path('password_reset/', PersonalizarReseteoContraseña.as_view(), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('admin/', admin.site.urls),
)

#para que solo se pueda acceder a rosetta si esta instalada en el proyecto
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

usuarios/urls.py
from django.contrib import admin
from django.urls import path
from .views import MyPerfilView, UpdatePerfilView, DeletePerfilView,PublicacionesMisContactosView, follow_perfiles_ajax, PerfilesDetailView

app_name = 'usuarios'

urlpatterns = [
    path('mi-perfil/<pk>/', MyPerfilView.as_view(), name = 'mi_perfil'),
    path('update-perfil/<pk>/', UpdatePerfilView.as_view(), name = 'update'),
    path('delete-perfil/<pk>/',DeletePerfilView.as_view() , name = 'delete'),
    path('publicaciones-mis-contactos/',PublicacionesMisContactosView.as_view() , name = 'mis_contactos'),
    path('follow/<pk>',follow_perfiles_ajax , name = 'follow'),
    path('perfiles-detail/<pk>',PerfilesDetailView.as_view() , name = 'detail'),
] 

publicaciones/forms.py
from django import forms
from .models import Publicacion, Comentario, RespuestaComentario

#formulario para editar una publicacion
class CreatePublicacionForm(forms.ModelForm):
    class Meta:
        model = Publicacion
        fields = [
            'titulo',
            'imagen',
            'video',
            'contenido',
        ]


#formulario para crear comentario en publicacion
class CreateComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = [
            'texto',
        ]

#formulario para contestar comentario de una publicacion
class ContestarComentarioForm(forms.ModelForm):
    class Meta:
        model = RespuestaComentario
        fields = [
            'respuesta',
        ]

stellarblade/forms/register_form.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from usuarios.models import PerfilUsuario
from django.utils.translation import gettext_lazy as _


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput(), label= _('Escriba su contraseña'))
    password_confirm = forms.CharField(widget = forms.PasswordInput(), label= _('Repita su contraseña'))
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password',
            'password_confirm',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = False#ponemos que el email no sea obligatorio

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if password != password_confirm and password != '':
            self.add_error('password_confirm',_('Las contraseñas no coinciden'))

        return cleaned_data

    def save(self, commit = True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])#encriptamoos la contraseña

        if commit:
            user.save()
            PerfilUsuario.objects.create(usuario = user)
        
        return user

stellarblade/forms/search_form.py
from django import forms
from django.utils.translation import gettext_lazy as _

class SearchForm(forms.Form):
    value = forms.CharField(label=_("Introduce la palabra a buscar"), max_length=150)

notificaciones/views.py
from django.shortcuts import render
from django.views.generic import CreateView, FormView, DetailView, UpdateView, DeleteView, ListView
from usuarios.models import PerfilUsuario, Follow
from publicaciones.models import Publicacion, Comentario, RespuestaComentario
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import NotificacionPublicacion, NotificacionComentario, NotificacionRespuestaComentario, NotificacionMeGusta, NotificacionSeguir, NotificacionMensaje
from django.shortcuts import get_object_or_404

@login_required
def list_notificaciones(request):
    return render(request, 'notificaciones/notificaciones.html')


@login_required
def marcar_notificacion_leida_comentario(request, pk):
    notificacion = NotificacionComentario.objects.get(pk = pk)
    if notificacion:
        notificacion.leida = True
        notificacion.save()
        return JsonResponse({
            'success': True,
            'mensaje': 'Notificacion leida correctamente'
        })
    else:
        return JsonResponse({
            'success': False,
            'mensaje': 'Notificacion no encontrada'
        })


@login_required
def marcar_notificacion_leida_publicacion(request, pk):
    notificacion = NotificacionPublicacion.objects.get(pk = pk)
    if notificacion:
        notificacion.leida = True
        notificacion.save()
        return JsonResponse({
            'success': True,
            'mensaje': 'Notificacion leida correctamente'
        })
    else:
        return JsonResponse({
            'success': False,
            'mensaje': 'Notificacion no encontrada'
        })


@login_required
def marcar_notificacion_leida_respuesta_comentario(request, pk):
    notificacion = NotificacionRespuestaComentario.objects.get(pk = pk)
    if notificacion:
        notificacion.leida = True
        notificacion.save()
        return JsonResponse({
            'success': True,
            'mensaje': 'Notificacion leida correctamente'
        })
    else:
        return JsonResponse({
            'success': False,
            'mensaje': 'Notificacion no encontrada'
        })


@login_required
def marcar_notificacion_leida_me_gusta(request, pk):
    notificacion = NotificacionMeGusta.objects.get(pk = pk)
    if notificacion:
        notificacion.leida = True
        notificacion.save()
        return JsonResponse({
            'success': True,
            'mensaje': 'Notificacion leida correctamente'
        })
    else:
        return JsonResponse({
            'success': False,
            'mensaje': 'Notificacion no encontrada'
        })


@login_required
def marcar_notificacion_leida_seguir(request, pk):
    notificacion = NotificacionSeguir.objects.get(pk = pk)
    if notificacion:
        notificacion.leida = True
        notificacion.save()
        return JsonResponse({
            'success': True,
            'mensaje': 'Notificacion leida correctamente'
        })
    else:
        return JsonResponse({
            'success': False,
            'mensaje': 'Notificacion no encontrada'
        })



@login_required
def marcar_notificacion_leida_mensajes(request, pk):
    notificacion = NotificacionMensaje.objects.get(pk = pk)
    if notificacion:
        notificacion.leida = True
        notificacion.save()
        return JsonResponse({
            'success': True,
            'mensaje': 'Notificacion leida correctamente'
        })
    else:
        return JsonResponse({
            'success': False,
            'mensaje': 'Notificacion no encontrada'
        })

stellarblade/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, SearchForm
from django.views.generic import CreateView, FormView, ListView
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.http import HttpResponse, HttpResponseRedirect
from publicaciones.models import Publicacion, Comentario, RespuestaComentario
from usuarios.models import Follow, PerfilUsuario
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.core.exceptions import PermissionDenied
from django.utils.translation import gettext_lazy as _


class HomeView(ListView):
    template_name = 'general/home.html'
    model = Publicacion

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["publicaciones"] = Publicacion.objects.all().exclude(autor=self.request.user.perfil).order_by('-fecha_publicacion') 
        else:
            context["publicaciones"] = Publicacion.objects.all().order_by('-fecha_publicacion')
        return context

def legal_view(request):
    return render(request, 'general/legal.html')

@login_required
def logout_view(request):
    logout(request)
    messages.success(request, _('Sesion cerrada con exito'))
    return HttpResponseRedirect(reverse_lazy('login'))

class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'general/registro.html'
    success_url = reverse_lazy('login')


    #redirigimos al usuario a su perfil en caso de que este logeado
    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            pk = self.request.user.perfil.pk
            return redirect(reverse_lazy('usuarios:mi_perfil' , kwargs={'pk': pk}))
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        messages.success(self.request, _('Usuario creado correctamente'))
        return super().form_valid(form)


class LoginView(FormView):
    template_name = 'general/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('home')

    #redirigimos al usuario a su perfil en caso de que este logeado
    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            pk = self.request.user.perfil.pk
            return redirect(reverse_lazy('usuarios:mi_perfil' , kwargs={'pk': pk}))
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        recuerdame = self.request.POST.get('recuerdame')
        if recuerdame:
            self.request.session.set_expiry(1209600)

        #obtenemos el usuario y comprobamos que ese usuario y contraseña coincide con alguno en la base de datos
        user = form.get_user()
        login(self.request, user)
        messages.success(self.request, _('Inicion de sesion exitoso.'))
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _('Contraseña o usuario incorrectos.'))
        return HttpResponseRedirect(reverse_lazy('login'))
        super().form_invalid(form)

@login_required
def search_view(request):
    if request.GET:
        formulario = SearchForm(request.GET)

        busqueda = formulario.data['value']#obtenemos lo que haya en el campo value del formulario

        publicaciones = Publicacion.objects.filter(titulo__icontains=busqueda)
        usuarios = PerfilUsuario.objects.filter(usuario__username__icontains=busqueda).exclude(usuario=request.user)# de esta forma accedemos al modelo PerfilUsuario para utilizar el include de _perfiles.html
        comentarios = Comentario.objects.filter(texto__icontains=busqueda)

        context ={
            'publicaciones': publicaciones,
            'usuarios': usuarios,
            'comentarios': comentarios,
            'formulario': formulario,
        }

        return render(request, 'general/busqueda.html', context)
    else:
        formulario = SearchForm()

        context = {
            'formulario': formulario
        }

        return render(request, 'general/busqueda.html', context)


#clase para personalizar los templates de recuperacion de contraseña
class PersonalizarReseteoContraseña(PasswordResetView):
    email_template_name = 'registration/password_reset_email.html'
    success_url = reverse_lazy('password_reset_done')
    template_name = 'registration/password_reset_form.html'


def info_del_juego(request):
    return render(request, 'general/info_del_juego.html')

def politica_legal(request):
    return render(request, 'general/politica_legal.html')

stellarblade/templates/_includes/_footer.html
{% load i18n %}

<p> &copy {% trans "Todos los derechos reservados - Consulta condiciones" %} <a href="{% url 'politica_legal' %}">{% trans "aqui" %}</a></p>

stellarblade/templates/_includes/_header.html
{% load static %}
{% load i18n %}

    <nav class="menu-header-movil">
        <ul>
            <li><a href="{% url 'info_del_juego' %}"><i class="bi bi-info-square"></i></a></li>
            <li><a href="{% url 'home' %}"><i class="bi bi-house"></i></a></li>
            {% if request.user.is_authenticated %}
                <li><a href="{% url 'usuarios:mis_contactos' %}"><i class="bi bi-person-add"></i></a></li>
                <li><a href="{% url 'search' %}"><i class="bi bi-search"></i></a></li>
                <li><a href="{% url 'usuarios:mi_perfil' request.user.perfil.pk %}">
                    {% if request.user.perfil.imagen_perfil %}
                        <img class="avatar-menu" src="{{request.user.perfil.imagen_perfil.thumbnails.xs.url}}" alt="">
                    {% else %}
                        <i class="bi bi-person-circle"></i>
                    {% endif %}
                </a></li>
                <li><a href="{% url 'mensajes:conversaciones' %}"><i class="bi bi-envelope"></i></a></li>
                <li class="numero-notificacion-container">
                    <a href="{% url 'notificaciones:lista' %}">
                        <i class="bi bi-bell"></i>
                    </a>
                    {% if request.user.perfil.total_notificaciones %}
                        <span class="numero-notificaciones">{{request.user.perfil.total_notificaciones}}</span>
                    {% endif %}
                </li>
            {% else %}
                <li><a href="{% url 'registro' %}"><i class="bi bi-plus-circle"></i></a></li>
                <li><a href="{% url 'login' %}"><i class="bi bi-rocket-takeoff"></i></a></li>
            {% endif %}
        </ul>
    </nav>


    <nav class="menu-header-tablet">
        <li class="logo-desktop-header">
            <a class="logo" href="{% url 'home' %}">
                <img src="{% static 'images/logo-stellar-blade-header-desktop.svg' %}" alt="">
            </a>
        </li>
        <ul>
            <li><a href="{% url 'info_del_juego' %}"><i class="bi bi-info-square"></i>{% trans "Info" %}</a></li>
            <li><a href="{% url 'home' %}"><i class="bi bi-house"></i>{% trans "Inicio" %}</a></li>
            {% if request.user.is_authenticated %}
                <li><a href="{% url 'usuarios:mis_contactos' %}"><i class="bi bi-person-add"></i>{% trans "Mi red" %}</a></li>
                <li><a href="{% url 'search' %}"><i class="bi bi-search"></i>{% trans "Busqueda" %}</a></li>
                <li><a href="{% url 'usuarios:mi_perfil' request.user.perfil.pk %}">
                    {% if request.user.perfil.imagen_perfil %}
                        <img class="avatar-menu" src="{{request.user.perfil.imagen_perfil.thumbnails.xs.url}}" alt="">
                    {% else %}
                    <i class="bi bi-person-circle"></i>
                    {% endif %}
                    {% trans "Mi Perfil" %}</a></li>
                <li><a href="{% url 'mensajes:conversaciones' %}"><i class="bi bi-envelope"></i>{% trans "Mensajes" %}</a></li>
                <li class="numero-notificacion-container">
                    <a href="{% url 'notificaciones:lista' %}">
                        <i class="bi bi-bell"></i>
                        {% trans "Notificaciones" %}</a>
                    {% if request.user.perfil.total_notificaciones %}
                        <span class="numero-notificaciones">{{request.user.perfil.total_notificaciones}}</span>
                    {% endif %}
                </li>
            {% else %}
                <li><a href="{% url 'registro' %}"><i class="bi bi-plus-circle"></i>{% trans "Registrate" %}</a></li>
                <li><a href="{% url 'login' %}"><i class="bi bi-rocket-takeoff"></i>{% trans "Accede a tu cuenta" %}</a></li>
            {% endif %}
        </ul>
    </nav>

stellarblade/templates/_includes/_messages.html
<div class="container-include-mensajes">
    {% for message in messages %}
    <div class="alert 
        {% if message.tags %}
            {% if message.tags == 'error' %}
                alert-danger
            {% else %}
                alert-{{message.tags}}
            {% endif %}
        {% else %}
            alert-info
        {% endif %}">
    {{message}}
    </div>
{% endfor %}
    <div class="mensaje-follow">
        
    </div>
    <div class="mensaje-likes">
        
    </div>
    <div class="mensajes-contestar-comentarios">
        
    </div>
    <div class="mensajes-eliminar-comentarios">
        
    </div>
    <div class="mensajes-eliminar-respuestas">
        
    </div>
    <div class="mensajes-eliminar-mensajes">
        
    </div>
    <div class="mensajes-eliminar-conversaciones">
        
    </div>
</div>

stellarblade/templates/_includes/_notificaciones.html
{% load i18n %}

<ul class="notificaciones">
    {% for noti in notificaciones_totales %}
    <li>
        <a data-href="{% url 'notificaciones:marcar_leida_'|add:noti.tipo noti.pk %}" 
        data-leida = "{{noti.leida}}" 
        class="notificacion" id="notificacion-{{noti.tipo}}-{{noti.pk}}" 
        data-noti-pk="{{noti.pk}}" 
        data-tipo = '{{noti.tipo}}'
        href="{{noti.url}}">{{noti}}. {% trans "Hace" %}:{{noti.fecha_notificacion | timesince}}
        </a>
    </li>
    {% endfor %}
</ul>

stellarblade/templates/_includes/_perfiles.html
{% load i18n %}

<article class="container-perfiles-includes">
    <div class="perfiles-includes-imagen-usuario">
        {% if perfil.imagen_perfil %}
            <a href="{% url 'usuarios:detail' perfil.pk %}">
                <img class="imagen-perfiles-movil" src="{{perfil.imagen_perfil.thumbnails.small.url}}" alt="{{perfil.usuario}}">
                <img class="imagen-perfiles-tablet" src="{{perfil.imagen_perfil.thumbnails.large.url}}" alt="{{perfil.usuario}}">
            </a>
        {% else %}
            <a href="{% url 'usuarios:detail' perfil.pk %}">
                <i class="bi bi-person-circle"></i>
            </a>
        {% endif %}
        <div class="usuario-seguidores">
            <h2>{{perfil.usuario}}</h2>
            <span id='Nseguidores-{{perfil.pk}}' >{% trans "Seguidores" %}: {{perfil.siguiendo.count}}</span>
        </div>
    </div>
    <p>{{perfil.biografia | truncatechars:50}}</p>
    <a class='ButtonFollows' data-perfil-id = {{perfil.pk}} href="{% url 'usuarios:follow' perfil.pk %}">
        {% if request.user.perfil in perfil.siguiendo.all %}
            <button class="boton-dejar-de-seguir">{% trans "Dejar de seguir" %}</button>
        {% else %}
            <button class="boton-seguir" >{% trans "Seguir" %}</button>
        {% endif %}
    </a>
</article>

stellarblade/templates/_includes/_publicaciones.html
{% load i18n %}

<article class="publicacion">
    <div class="imagen-hora-titulo">
        <div class="imagen">
            {% if publicacion.autor.imagen_perfil %}
                <a href="{% url 'usuarios:detail' publicacion.autor.pk %}">
                    <img loading="lazy" class="imagen-perfil-movil" src="{{publicacion.autor.imagen_perfil.thumbnails.small.url}}" alt="{{publicacion.autor.usuario}}">
                    <img loading="lazy" class="imagen-perfil-tablet" src="{{publicacion.autor.imagen_perfil.thumbnails.large.url}}" alt="{{publicacion.autor.usuario}}">
                </a>
            {% else %}
                <a href="{% url 'usuarios:detail' publicacion.autor.pk %}">
                    <i class="bi bi-person-circle"></i>
                </a>
            {% endif %}
        </div>
        <div class="hora-autor-titulo">
            <div class="hora-autor">
                <a href="{% url 'usuarios:detail' publicacion.autor.pk %}">{{publicacion.autor}}</a>
                <span> - {{publicacion.fecha_publicacion | timesince}}</span>
            </div>
            <div class="titulo">
                <h2>{{publicacion.titulo}}</h2>
            </div>
        </div>
    </div>
    {% if publicacion.imagen %}
        <img loading="lazy" class="imagen_publicacion_movil" src="{{publicacion.imagen.thumbnails.movilpublicacion.url}}" alt="{{publicacion.autor.usuario}}">
        <img loading="lazy" class="imagen_publicacion_tablet" src="{{publicacion.imagen.thumbnails.largepublicacion.url}}" alt="{{publicacion.autor.usuario}}">
    {% endif %}
    {% if publicacion.video %}
    <video class="video-publicacion-include" controls autoplay muted>
        <source src="{{publicacion.video.url}}" type="video/mp4">
        {% trans "Tu navegador no soporta el vídeo." %}
    </video>
    {% endif %}
    <p class="contenido-publicacion" >{{publicacion.contenido | truncatechars:10}}</p>
    <div class="numero-likes-comentarios">
        <div class="numero-likes">
            <span id="NumeroLikes-{{publicacion.pk}}">{{publicacion.likes.count}}</span>
            <a class="LikesButtons" data-publicacion-id = {{publicacion.pk}} href="{% url 'publicaciones:like' publicacion.pk %}">
                {% if request.user.perfil in publicacion.likes.all %}
                    <i class="bi bi-heart-fill"></i>
                {% else %}
                    <i class="bi bi-heart"></i>
                {% endif %}
            </a>
        </div>
        <div class="numero-comentarios">
            <span>{{publicacion.total_comentarios}}
                {% if publicacion.comentarios.count %}
                    <i class="bi bi-chat-dots-fill"></i>
                {% else %}
                    <i class="bi bi-chat-dots"></i>
                {% endif %}
            </span>
        </div>
    </div>
    <a class="boton-detalle" href="{% url 'publicaciones:detalle' publicacion.pk %}">{% trans "Detalle de publicación" %}</a>
</article>