mensajes/urls.py
from django.contrib import admin
from django.urls import path
from .views import CreateMensajeView, ConversacionesView, ConversacionesDetailView, contestar_mensaje, eliminar_mensaje, eliminar_conversacion


app_name = 'mensajes'

urlpatterns = [
    path('conversaciones/', ConversacionesView.as_view(), name = 'conversaciones'),
    path('conversaciones-detail/<pk>', ConversacionesDetailView.as_view(), name = 'conversaciones_detail'),
    path('nuevo/<pk>/', CreateMensajeView.as_view(), name = 'nuevo'),
    path('contestar-mensaje/<pk>/', contestar_mensaje, name = 'contestar_mensaje'),
    path('eliminar-mensaje/<pk>/', eliminar_mensaje, name = 'eliminar_mensaje'),
    path('eliminar-conversacion/<pk>/', eliminar_conversacion, name = 'eliminar_conversacion'),
] 

publicaciones/urls.py
from django.contrib import admin
from django.urls import path
from .views import CrearPublicacionView, DetailPublicacionView, UpdatePublicacionView, DeletePublicacionView, like_ajax, contestar_comentario_ajax, eliminar_comentario, eliminar_respuesta_comentario


app_name = 'publicaciones'

urlpatterns = [
    path('like/<pk>/', like_ajax, name = 'like'),
    path('contestar-comentario/<pk>/', contestar_comentario_ajax, name = 'contestar_comentario'),
    path('eliminar-comentario/<pk>/', eliminar_comentario, name = 'eliminar_comentario'),
    path('eliminar-respuesta-comentario/<pk>/', eliminar_respuesta_comentario, name = 'eliminar_respuesta'),
    path('crear/', CrearPublicacionView.as_view(), name = 'crear'),
    path('detalle/<pk>', DetailPublicacionView.as_view(), name = 'detalle'),
    path('editar/<pk>', UpdatePublicacionView.as_view(), name = 'editar'),
    path('eliminar/<pk>', DeletePublicacionView.as_view(), name = 'delete'),
] 

stellarblade/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import legal_view, logout_view, RegisterView, LoginView, HomeView, search_view, PersonalizarReseteoContraseña, info_del_juego, politica_legal
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns#tenemos que importar esto para que funcione la traduccion


urlpatterns = [#aqui metemos las que no queremos que sean traducibles
    path('i18n/', include('django.conf.urls.i18n')),#esto nos incluye la vista set_language,viene propia de django
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += i18n_patterns (
    path('', HomeView.as_view(), name = 'home'),
    path('informacion-stellar-blade/', info_del_juego, name = 'info_del_juego'),
    path('politica-legal/', politica_legal, name = 'politica_legal'),
    path('logout/', logout_view, name = 'logout'),
    path('search/', search_view, name = 'search'),
    path('registro/', RegisterView.as_view(), name = 'registro'),
    path('login/', LoginView.as_view(), name = 'login'),
    path('usuarios/', include('usuarios.urls', namespace = 'usuarios')),
    path('publicaciones/', include('publicaciones.urls', namespace = 'publicaciones')),
    path('notificaciones/', include('notificaciones.urls', namespace = 'notificaciones')),
    path('mensajes/', include('mensajes.urls', namespace = 'mensajes')),
    path('password_reset/', PersonalizarReseteoContraseña.as_view(), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('admin/', admin.site.urls),
)

#para que solo se pueda acceder a rosetta si esta instalada en el proyecto
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

usuarios/urls.py
from django.contrib import admin
from django.urls import path
from .views import MyPerfilView, UpdatePerfilView, DeletePerfilView,PublicacionesMisContactosView, follow_perfiles_ajax, PerfilesDetailView

app_name = 'usuarios'

urlpatterns = [
    path('mi-perfil/<pk>/', MyPerfilView.as_view(), name = 'mi_perfil'),
    path('update-perfil/<pk>/', UpdatePerfilView.as_view(), name = 'update'),
    path('delete-perfil/<pk>/',DeletePerfilView.as_view() , name = 'delete'),
    path('publicaciones-mis-contactos/',PublicacionesMisContactosView.as_view() , name = 'mis_contactos'),
    path('follow/<pk>',follow_perfiles_ajax , name = 'follow'),
    path('perfiles-detail/<pk>',PerfilesDetailView.as_view() , name = 'detail'),
] 

publicaciones/forms.py
from django import forms
from .models import Publicacion, Comentario, RespuestaComentario

#formulario para editar una publicacion
class CreatePublicacionForm(forms.ModelForm):
    class Meta:
        model = Publicacion
        fields = [
            'titulo',
            'imagen',
            'video',
            'contenido',
        ]


#formulario para crear comentario en publicacion
class CreateComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = [
            'texto',
        ]

#formulario para contestar comentario de una publicacion
class ContestarComentarioForm(forms.ModelForm):
    class Meta:
        model = RespuestaComentario
        fields = [
            'respuesta',
        ]

stellarblade/forms/register_form.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from usuarios.models import PerfilUsuario
from django.utils.translation import gettext_lazy as _


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput(), label= _('Escriba su contraseña'))
    password_confirm = forms.CharField(widget = forms.PasswordInput(), label= _('Repita su contraseña'))
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password',
            'password_confirm',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = False#ponemos que el email no sea obligatorio

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if password != password_confirm and password != '':
            self.add_error('password_confirm',_('Las contraseñas no coinciden'))

        return cleaned_data

    def save(self, commit = True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])#encriptamoos la contraseña

        if commit:
            user.save()
            PerfilUsuario.objects.create(usuario = user)
        
        return user

stellarblade/forms/search_form.py
from django import forms
from django.utils.translation import gettext_lazy as _

class SearchForm(forms.Form):
    value = forms.CharField(label=_("Introduce la palabra a buscar"), max_length=150)

stellarblade/forms/update_perfil_form.py
from django import forms
from django.contrib.auth.models import User
from usuarios.models import PerfilUsuario
from django.utils.translation import gettext_lazy as _


#clase para poder editar el perfil en la edicion del perfil del usuario logeado
class PerfilUsuarioForm(forms.ModelForm):
    email = forms.EmailField(required=False, label=_('Email (opcional)'))

    class Meta:
        model = PerfilUsuario
        fields = [
            'imagen_perfil',
            'biografia',
            'fecha_nacimiento',
        ]

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if self.user:
            self.fields['email'].initial = self.user.email

    def save(self, commit=True):
        perfil = super().save(commit=False)
        if commit:
            perfil.save()
            if self.user:
                self.user.email = self.cleaned_data['email']
                self.user.save()
        return perfil

publicaciones/views.py
from django.shortcuts import render
from django.views.generic import CreateView, FormView, DetailView, UpdateView, DeleteView, ListView
from usuarios.models import PerfilUsuario, Follow
from .models import Publicacion, Comentario, RespuestaComentario
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User
from django.http import JsonResponse
from .forms import CreatePublicacionForm, CreateComentarioForm, ContestarComentarioForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from notificaciones.models import NotificacionPublicacion, NotificacionComentario, NotificacionRespuestaComentario, NotificacionMeGusta
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext_lazy as _


@method_decorator(login_required, name='dispatch')
class CrearPublicacionView(CreateView):
    template_name = 'publicaciones/publicacion_nueva.html'
    model = Publicacion
    form_class = CreatePublicacionForm

    def form_valid(self, form):
        nueva_publicacion = form.save(commit=False)
        nueva_publicacion.autor = self.request.user.perfil
        nueva_publicacion.save()#nos aseguramos de redirigir al usuario a la nueva publicacion creada en succes_url
        titulo = nueva_publicacion.titulo
        perfil_usuario = self.request.user.perfil
        seguidores = perfil_usuario.siguiendo.all()
        for seguidor in seguidores:
            NotificacionPublicacion.objects.create(autor=perfil_usuario, publicacion=nueva_publicacion, destinatario=seguidor, url= reverse_lazy('publicaciones:detalle', kwargs= {'pk': nueva_publicacion.pk}))

        messages.success(self.request, _('Publicacion creada correctamente'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('publicaciones:detalle', kwargs={'pk': self.object.pk})


class DetailPublicacionView(DetailView, CreateView):
    template_name = 'publicaciones/publicacion_detail.html'
    model = Publicacion
    context_object_name = 'publicacion'
    form_class = CreateComentarioForm

    def form_valid(self, form):
        form.instance.publicacion = self.get_object()
        form.instance.autor = self.request.user.perfil
        perfil_usuario = self.request.user.perfil
        publicacion = self.get_object()
        destinatario = publicacion.autor
        if self.request.user.perfil != publicacion.autor:
            NotificacionComentario.objects.create(autor=perfil_usuario, destinatario=destinatario, publicacion=publicacion, url=reverse_lazy('publicaciones:detalle', kwargs= {'pk': publicacion.pk}))
        messages.success(self.request ,_('Comentario añadido correctamente'))
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('publicaciones:detalle', args=[self.get_object().pk])


@method_decorator(login_required, name='dispatch')
class UpdatePublicacionView(UpdateView):
    template_name = 'publicaciones/publicacion_update.html'
    model = Publicacion
    fields = [
        'titulo',
        'imagen',
        'video',
        'contenido',
    ]

    #solo se puede editar si el usuario logeado es el autor de la publicacion
    def dispatch(self, request, *args, **kwargs):
        usuario_perfil = self.get_object()
        if usuario_perfil.autor != self.request.user.perfil:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)
    

    def form_valid(self, form):
        messages.success(self.request, _('Publicacion editada correctamente'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('publicaciones:detalle', kwargs={'pk': self.object.pk})


@method_decorator(login_required, name='dispatch')
class DeletePublicacionView(DeleteView):
    template_name = 'publicaciones/publicacion_delete.html'
    model = Publicacion

    def dispatch(self, request, *args, **kwargs):
        usuario_perfil = self.get_object()
        if usuario_perfil.autor != self.request.user.perfil:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        publicacion = Publicacion.objects.get(pk = self.object.pk)
        NotificacionPublicacion.objects.filter(publicacion=publicacion).delete()
        publicacion.delete()
        messages.success(self.request, _('Publicacion eliminada correctamente.'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('usuarios:mi_perfil', kwargs={'pk': self.request.user.perfil.pk})


@login_required
def contestar_comentario_ajax(request, pk):
    if request.method == 'POST':
        comentario = get_object_or_404(Comentario, pk=pk)  
        respuesta = request.POST.get('respuesta')
        pkPublicacion = request.POST.get('publicacion_pk')
        publicacion = Publicacion.objects.get(pk=pkPublicacion)
        if respuesta:
            RespuestaComentario.objects.create(autor=request.user.perfil, publicacion=publicacion, comentario=comentario, respuesta=respuesta)

            NotificacionRespuestaComentario.objects.create(comentario=comentario, destinatario=comentario.autor, usuario=request.user.perfil, publicacion=publicacion, url=reverse_lazy('publicaciones:detalle', kwargs={'pk': pkPublicacion}))

            return JsonResponse({
            'mensaje': _('Se ha contestado al comentario de: %(autor)s') % {
                'autor': comentario.autor
            },
            'respuesta': respuesta,
            'autor': request.user.username,
            })
        else:
            return JsonResponse({
            'mensaje': _('No se ha podido contestar al comentario de: %(autor)s') % {
                'autor': comentario.autor
            }
            })


@login_required
def like_ajax(request, pk):
    publicacion = Publicacion.objects.get(pk = pk)
    if request.user.perfil in publicacion.likes.all():
        request.user.perfil.unlike_pub(publicacion)
        NotificacionMeGusta.objects.filter(publicacion=publicacion, destinatario=publicacion.autor, usuario=request.user.perfil, url= reverse_lazy('publicaciones:detalle', kwargs={'pk': publicacion.pk})).delete()
        return JsonResponse({
            'like': False,
            'mensaje': _('Se ha quitado like en la siguiente publicacion: %(publicacion)s') % {
                'publicacion': publicacion.titulo
            },
            'numero_likes': publicacion.likes.all().count()
        })
    else:
        request.user.perfil.like_pub(publicacion)
        if request.user.perfil != publicacion.autor:
            NotificacionMeGusta.objects.create(publicacion=publicacion, destinatario=publicacion.autor, usuario=request.user.perfil, url= reverse_lazy('publicaciones:detalle', kwargs={'pk': publicacion.pk}))
        return JsonResponse({
            'like': True,
            'mensaje': _('Se ha dado like a la siguiente publicacion: %(publicacion)s') % {
                'publicacion': publicacion.titulo
            },
            'numero_likes': publicacion.likes.all().count()
        })


@login_required
def eliminar_comentario(request, pk):
    if request.method == 'DELETE':
        comentario = Comentario.objects.get(pk = pk)
        if request.user.perfil == comentario.autor:
            NotificacionComentario.objects.filter(autor=comentario.autor, publicacion=comentario.publicacion).delete()
            comentario.delete()
            return JsonResponse({
                'success': True,
                'mensaje': _('Se ha eliminado el comentario')
            })
        else:
            return JsonResponse({
                'success': False,
                'mensaje': _('No se ha podido eliminar el comentario')
            })


@login_required
def eliminar_respuesta_comentario(request, pk):
    if request.method == 'DELETE':
        respuesta_comentario = RespuestaComentario.objects.get(pk = pk)
        if request.user.perfil == respuesta_comentario.autor:
            NotificacionRespuestaComentario.objects.filter(usuario=respuesta_comentario.autor, publicacion=respuesta_comentario.publicacion).delete()
            respuesta_comentario.delete()
            return JsonResponse({
                'success': True,
                'mensaje': _('Se ha eliminado la respuesta'),
            })
        else:
            return JsonResponse({
                'success': False,
                'mensaje': _('No se ha podido eliminar la respuesta'),
            })

stellarblade/templates/publicaciones/publicacion_delete.html
{% extends "general/layout.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block head_title %}Stellar Blade{% endblock  %}
{% block description %}{% trans "Pagina donde se eliminar una publicación deseada" %}{% endblock %}
{% block page_title %}{% trans "Eliminar publicación" %}{% endblock  %}
{% block page_content %}
<div class="container-eliminar-publicacion">
    <h4 class="title-eliminar-publicacion">¿{% trans "Seguro que desea eliminar la publicacion" %}: <strong>{{object.titulo}}</strong>?</h4>
    <form class="formulario-eliminar-publicacion" action="" method = 'POST'>
        {% csrf_token %}
        {{form}}
        <button class="boton-eliminar">{% trans "Eliminar" %}</button>
        <a class="boton-cancelar" href="{% url 'publicaciones:detalle' object.pk %}">{% trans "Cancelar" %}</a>
    </form>
</div>
{% endblock  %}

stellarblade/templates/publicaciones/publicacion_detail.html
{% extends "general/layout.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block head_title %}Stellar Blade{% endblock  %}
{% block description %}{{publicacion.titulo}} - {{publicacion.contenido | truncatechars:20}}{% endblock %}
{% block page_title %}{% trans "DETALLE PUBLICACION" %}{% endblock %}
{% block page_content %}
<div class="container-detalle-publicacion">
    <div class="publicacion-detalle-imagen-descripcion">
        <div class="imagen-publicacion-detalle">
            {% if publicacion.autor.imagen_perfil %}
                <a href="{% url 'usuarios:detail' publicacion.autor.pk %}"><img loading="lazy" src="{{publicacion.autor.imagen_perfil.thumbnails.small.url}}" alt="{{publicacion.autor.usuario}}"></a>
            {% else %}
            <a href="{% url 'usuarios:detail' publicacion.autor.pk %}">
                <i class="bi bi-person-circle"></i>
            </a>
            {% endif %}
        </div>
        <div class="descripcion-publicacion-detalle" >
            <p class="autor-fecha" >{{publicacion.autor}} - {% trans "Hace" %}: {{publicacion.fecha_publicacion | timesince}}</p>
            <p class="titulo" >{{publicacion.titulo}}</p>
        </div>
    </div>

    <div class="container-media-detalle-publicacion">
        <div class="publicacion-detalle-imagen-large">
            {% if publicacion.imagen %}
                <img loading="lazy" class="zoom-modal" src="{{publicacion.imagen.url}}" alt="{{publicacion.titulo}}">
                <div id="image-modal" class="modal">
                    <span class="close" onclick="closeModal()">X</span>
                    <a class="descargar-imagen" href="{{publicacion.imagen.url}}" download><i class="bi bi-download"></i></a>
                    <img loading="lazy" class="contenido-modal" id="image-in-modal">
                </div>
            {% endif %}
        </div>
    
        <div class="publicacion-detalle-video">
            {% if publicacion.video %}
            <video class="video-publicacion-detalle" controls autoplay muted>
                <source src="{{publicacion.video.url}}" type="video/mp4">
                {% trans "Tu navegador no soporta el video." %}
            </video>
            {% endif %}
        </div>
    </div>

    <div class="publicacion-detalle-contenido">
        <p>{{publicacion.contenido}}</p>
    </div>

    <div class="publicacion-detalle-likes-comentarios">
        <div class="likes">
            <span id="NumeroLikes-{{publicacion.pk}}">{{publicacion.likes.count}}</span>
            <a class="LikesButtons" data-publicacion-id = {{publicacion.pk}} href="{% url 'publicaciones:like' publicacion.pk %}">
                {% if request.user.perfil in publicacion.likes.all %}
                    <i class="bi bi-heart-fill"></i>
                {% else %}
                    <i class="bi bi-heart"></i>
                {% endif %}
            </a>
        </div>
        <div class="comentarios">
            <button class="ButtonNuevoComentario" >{{publicacion.total_comentarios}}
                {% if publicacion.comentarios.count %}
                    <i class="bi bi-chat-dots-fill"></i>
                {% else %}
                    <i class="bi bi-chat-dots"></i>
                {% endif %}
            </button>
        </div>
    </div>

    {% if publicacion.comentarios.count %}
        <div class="publicacion-detalle-comentarios-respuestas">
            <h3>{% trans "Comentarios de la publicación" %}</h3>
            {% for comentario in publicacion.comentarios.all %}
            <article class="container-comentarios-respuestas">
                
                <div class="container-comentarios" id="container-comentario-{{comentario.pk}}">
                    <div class="imagen-autor-fecha-publi">
                        <a href="{% url 'usuarios:detail' comentario.autor.pk %}">
                            {% if comentario.autor.imagen_perfil %}
                                <img src="{{comentario.autor.imagen_perfil.thumbnails.xs.url}}" alt="{{comentario.autor.usuario}}">
                            {% else %}
                                <i class="bi bi-person-circle"></i>
                            {% endif %}
                        </a>
                        <div class="autor-fecha-publi">
                            <p class="autor">{{comentario.autor.usuario}}</p>
                            <p class="fecha-publi">{% trans "Hace" %}: {{comentario.fecha_comentario | timesince}}</p>
                        </div>
                    </div>
                    <p class="TextoComentario" >{{comentario.texto}}</p>
                    {% if comentario.autor == request.user.perfil %}
                        <button data-comentario-pk="{{comentario.pk}}" class="EliminarComentario" data-href="{% url 'publicaciones:eliminar_comentario' pk=comentario.pk %}" data-redirect-url="{% url 'publicaciones:detalle' publicacion.pk %}">{% trans "Eliminar" %}</button>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        {% if comentario.autor != request.user.perfil %}
                            <button data-comentario-pk={{comentario.pk}} class="BotonResponder" >{% trans "Responder" %}</button>
                        {% endif %}
                    {% endif %}
                    {% if comentario.respuestas.count %}
                        <button class="VerRespuestas" data-comentario-pk="{{comentario.pk}}">{% trans "Ver respuestas" %}</button>
                    {% endif %}
                </div>

                {% if comentario.respuestas.count %}
                <div class="container-respuestas"  id="container-respuestas-{{comentario.pk}}">
                    {% for respuesta in comentario.respuestas.all  %}
                        <div id="container-respuesta-{{respuesta.pk}}">
                            <div class="imagen-autor-fecha-respuesta">
                                <a href="{% url 'usuarios:detail' respuesta.autor.pk %}">
                                    {% if respuesta.autor.imagen_perfil %}
                                        <img src="{{respuesta.autor.imagen_perfil.thumbnails.xs.url}}" alt="{{comentario.autor.usuario}}">
                                    {% else %}
                                        <i class="bi bi-person-circle"></i>
                                    {% endif %}
                                </a>
                                <div class="autor-fecha-respuesta">
                                    <p class="autor">{{respuesta.autor.usuario}}</p>
                                    <p class="fecha-respuesta">{% trans "Hace" %}: {{respuesta.fecha_respuesta | timesince}}</p>
                                </div>
                            </div>
                            <p class="TextoRespuesta">{{respuesta}}</p>
                            {% if request.user.perfil == respuesta.autor %}
                                <button class="eliminarRespuesta" data-respuesta-pk="{{respuesta.pk}}" data-href="{% url 'publicaciones:eliminar_respuesta' respuesta.pk %}" data-redirect-url="{% url 'publicaciones:detalle' publicacion.pk %}">{% trans "Eliminar" %}</button>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                {% endif %}

                <form class='FormRespuesta' id="FormRespuesta-{{comentario.pk}}" method="POST" action="{% url 'publicaciones:contestar_comentario' comentario.pk%}" data-redirect-url="{% url 'publicaciones:detalle' publicacion.pk %}">
                    {% csrf_token %}
                    <input type="hidden" name="publicacion_pk" value="{{publicacion.pk}}">
                    {{contestar_form.respuesta | as_crispy_field}}
                    <button class="boton-responder">{% trans "Responder" %}</button>
                </form>
            </article>
            {% endfor %}
        </div>
    {% else %}
        <h3 class="title-no-hay-comentarios">{% trans "En esta publicación todavía no hay comentarios" %}</h3>
    {% endif %}

    {% if request.user.is_authenticated %}
    <div class="FormComentario">
        <form class="formulario-comentar" action="" method='POST' >
            {% csrf_token %}
            {{form.texto | as_crispy_field}}
            <button class="boton-comentar" >{% trans "Comentar" %}</button>
        </form>
    </div>
    {% endif %}

    {% if publicacion.autor == request.user.perfil %}
        <div class="botones-editar-eliminar-publicacion-detalle">
            <a class="boton-editar" href="{% url 'publicaciones:editar' publicacion.pk %}">{% trans "Editar" %}</a>
            <a class="boton-eliminar" href="{% url 'publicaciones:delete' publicacion.pk %}">{% trans "Eliminar" %}</a>
        </div>
    {% endif %}
</div>
{% endblock  %}

stellarblade/templates/publicaciones/publicacion_nueva.html
{% extends "general/layout.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block head_title %}Stellar Blade{% endblock  %}
{% block description %}{% trans "Pagina de creacion de publicación" %}{% endblock %}
{% block page_title %}{% trans "PUBLICACION NUEVA" %}{% endblock  %}
{% block page_content %}
<div class="container-publicacion-nueva">
    <form class="formulario-para-crear-publicacion" action="" method = 'POST' enctype='multipart/form-data'>
        {% csrf_token %}
        {{form.titulo | as_crispy_field}}
        {{form.imagen | as_crispy_field}}
        {{form.video | as_crispy_field}}
        {{form.contenido | as_crispy_field}}
        <button class="boton-crear">{% trans "Crear publicación" %}</button>
    </form>
</div>
{% endblock  %}

stellarblade/templates/publicaciones/publicacion_update.html
{% extends "general/layout.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block head_title %}Stellar Blade{% endblock  %}
{% block description %}{% trans "Pagina de edición de una publicación existente" %}{% endblock %}
{% block page_title %}{% trans "Editar Publicación" %}{% endblock  %}
{% block page_content %}
<div class="container-editar-publicacion">
    <form class="formulario-editar-publicacion" action="" method = 'POST' enctype='multipart/form-data'>
        {% csrf_token %}
        {{form.titulo | as_crispy_field}}
        {{form.imagen | as_crispy_field}}
        {{form.video | as_crispy_field}}
        {{form.contenido | as_crispy_field}}
        <button class="boton-editar">{% trans "Editar" %}</button>
        <a class="boton-cancelar" href="{% url 'publicaciones:detalle' object.pk %}">{% trans "Cancelar" %}</a>
    </form>
</div>
{% endblock  %}